### ISSUE TITLE
Irregular H1 padding on tablet/mobile

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#136]
On mobile/tablet there is a large amount of left-hand padding that pushes the titles to the right.  Not sure if there is a reason for this, but looks like it can be removed from masterbar.css.  I'll create a separate issue with Jetpack, but we may want to override here in the meantime.

```css
.wp-admin .wrap h1, .wp-admin .wrap h2 {
    padding-left: 50px;
}
```

<img width="712" alt="screen shot 2018-11-02 at 9 39 32 am" src="https://user-images.githubusercontent.com/10561050/47921965-e0e53580-de83-11e8-81f9-a8afce9b79f8.png">
