### ISSUE TITLE
Grid icons are all too small

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#386]
Unclear why this regression has occurred, but the grid icons should mostly be set to 24px.  Need to investigate if there's a reason for setting the default to 18px.

```css
.wp-admin .gridicon,
.wp-admin .gridicon {
	vertical-align: middle;
	width: 18px;
	height: 18px;
	fill: #537994;
}
```

#### Current
<img width="149" alt="screen shot 2018-11-30 at 10 55 42 am" src="https://user-images.githubusercontent.com/10561050/49265875-e9368d80-f48e-11e8-8c55-bdf7988af765.png">

#### Correct
<img width="191" alt="screen shot 2018-11-30 at 10 58 28 am" src="https://user-images.githubusercontent.com/10561050/49265873-e76cca00-f48e-11e8-95c6-5d0bbfe4d1bf.png">
